---
build_from:
  amd64: nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04
  aarch64: nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  WYOMING_WHISPER_VERSION: 2.5.0
